name: "Upload"

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: pocket-apps/action-update-version@v1
      with:
        files: 'setup.py'
        version-regexp: '\d+.\d+.\d+'
        repo-token: ${{ secrets.GH_TOKEN }}

    - name: Build the executable
      run: python3 -m pip install twine && python3 setup.py sdist && ./setup.py patch

    - name: Publish a Python distribution to PyPI
      if: false #and github.event_name == 'push'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
